### ISSUE TITLE
Any contract with this spec alive?

### ISSUE THREAD

**Issue by chendatony31** [EOSIO/ricardian-spec#19]
I'm testing push action with EOSIO's new [Chrome Extension](https://github.com/EOSIO/eosio-reference-chrome-extension-authenticator-app). But i can't find any contract can meet the requirement. Any idea?

**Comment by TaraTritt** [comment]
Hi @chendatony31, please check out [Tropical Example](https://github.com/EOSIO/tropical-example-web-app) and follow the steps in [Running Tropical Example](https://github.com/EOSIO/tropical-example-web-app#running-tropical-example) to get started. Tropical Example setups a local chain and deploys a contract with an abi that follows the Ricardian Specification. We will be update the chrome extension repository to reference Tropical Example moving forward, thanks!
